apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp2  # You can also try 'gp3' if it fits your requirements
  fsType: ext4
reclaimPolicy: Delete  # Consider using 'Delete' for dynamic provisioning
volumeBindingMode: WaitForFirstConsumer  # Uncomment this line if necessary
